"""alter llm_traces document_id nullable=true

Revision ID: 3f857fb4785e
Revises: ea3966f718f1
Create Date: 2026-03-09 05:16:54.897954+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f857fb4785e"
down_revision: Union[str, Sequence[str], None] = "ea3966f718f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "llm_traces",
        "document_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="文档 ID",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "llm_traces",
        "document_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="文档 ID",
    )
    # ### end Alembic commands ###
