"""alter conversations

Revision ID: ea3966f718f1
Revises: aa8e24d1861f
Create Date: 2026-03-09 03:46:26.001815+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea3966f718f1'
down_revision: Union[str, Sequence[str], None] = 'aa8e24d1861f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='关联的多个文档 ID 列表'))
    op.alter_column('conversations', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='关联文档 ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='关联文档 ID')
    op.drop_column('conversations', 'document_ids')
    # ### end Alembic commands ###
