"""add llm_traces

Revision ID: aa8e24d1861f
Revises: d29c95bb7fbf
Create Date: 2026-03-08 07:03:10.253203+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa8e24d1861f"
down_revision: Union[str, Sequence[str], None] = "d29c95bb7fbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_traces",
        sa.Column("session_id", sa.String(length=64), nullable=False, comment="会话 ID"),
        sa.Column("document_id", sa.Integer(), nullable=False, comment="文档 ID"),
        sa.Column("question", sa.Text(), nullable=False, comment="用户问题"),
        sa.Column(
            "retrieved_chunks", sa.Text(), nullable=True, comment="检索到的切片内容（JSON）"
        ),
        sa.Column("prompt", sa.Text(), nullable=True, comment="发送给 LLM 的完整 Prompt"),
        sa.Column("answer", sa.Text(), nullable=True, comment="LLM 回答"),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True, comment="输入 token 数"),
        sa.Column(
            "completion_tokens", sa.Integer(), nullable=True, comment="输出 token 数"
        ),
        sa.Column("latency_ms", sa.Float(), nullable=True, comment="耗时（毫秒）"),
        sa.Column("model_name", sa.String(length=64), nullable=True, comment="模型名称"),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="状态 success/failed"
        ),
        sa.Column("error_msg", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_traces_document_id"), "llm_traces", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_llm_traces_session_id"), "llm_traces", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_traces_session_id"), table_name="llm_traces")
    op.drop_index(op.f("ix_llm_traces_document_id"), table_name="llm_traces")
    op.drop_table("llm_traces")
    # ### end Alembic commands ###
