"""create documents and conversations

Revision ID: d688190eae3e
Revises:
Create Date: 2026-03-05 20:59:14.193224+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d688190eae3e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("filename", sa.String(length=255), nullable=False, comment="原始文件名"),
        sa.Column(
            "file_type",
            sa.String(length=20),
            nullable=False,
            comment="文件类型 pdf/docx/txt",
        ),
        sa.Column("file_size", sa.BigInteger(), nullable=False, comment="文件大小（字节）"),
        sa.Column(
            "chunk_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="切片数量",
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "DONE", "FAILED", name="documentstatus"),
            nullable=False,
            comment="处理状态",
        ),
        sa.Column("error_msg", sa.Text(), nullable=True, comment="失败原因"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversations",
        sa.Column("session_id", sa.String(length=64), nullable=False, comment="会话 ID"),
        sa.Column("document_id", sa.Integer(), nullable=False, comment="关联文档 ID"),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", name="messagerole"),
            nullable=False,
            comment="消息角色",
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="消息内容"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主键 ID"
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_session_id"),
        "conversations",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_session_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("documents")
    # ### end Alembic commands ###
